### ISSUE TITLE
merlin_shortened.csv	ilegal quotes

### ISSUE THREAD

**Issue by robsontenorio** [abrakam/Faeria_Cards#6]
Hi,
The file merlin_shortened.csv has some line has double quotes, what makes CSV invalid.

**Comment by robsontenorio** [comment]
Hi,  "merlin" has doubled cards. How to recognize the active one? By looking text, CARD_ID = 313 is the newest.

`Ex: twinsoul`

**Comment by Tidwell** [comment]
It's been that way for quite a while, I'm assuming because thats the format they need to parse in unity.  Its a bit more work, but you can pretty easily parse it by splitting on newlines then blowing apart each line on semicolons.  An example:

https://github.com/Tidwell/faeria-cards/blob/master/parse-csv.js
